version: '3.8'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
